"""Build the Font Awesome subset used by the site.

Reads the full Font Awesome Pro kit (kept OUTSIDE the repo, commercial license)
and writes only the glyphs listed in scripts/icons.txt:

  src/assets/fonts/fa-{solid-900,regular-400,brands-400}.woff2
  src/styles/icons.css

Usage:  python scripts/subset-icons.py [path-to-fontawesome-pro]
Needs:  pip install fonttools brotli
"""

import re
import sys
from pathlib import Path

from fontTools import subset

ROOT = Path(__file__).resolve().parent.parent
FA = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT.parent / 'fonts' / 'fontawesome-pro'
CSS_IN = FA / 'css' / 'fontawesome.all.min.css'
FONTS_OUT = ROOT / 'src' / 'assets' / 'fonts'
CSS_OUT = ROOT / 'src' / 'styles' / 'icons.css'

# style in icons.txt -> (font file, @font-face family, weight)
STYLES = {
    'solid': ('fa-solid-900.woff2', 'Font Awesome 7 Pro', 900),
    'regular': ('fa-regular-400.woff2', 'Font Awesome 7 Pro', 400),
    'brands': ('fa-brands-400.woff2', 'Font Awesome 7 Brands', 400),
}


def top_level_blocks(css: str) -> list[str]:
    """Split minified CSS into top-level statements (rules and at-rule blocks)."""
    blocks, depth, start = [], 0, 0
    for i, ch in enumerate(css):
        if ch == '{':
            depth += 1
        elif ch == '}':
            depth -= 1
            if depth == 0:
                blocks.append(css[start:i + 1].strip())
                start = i + 1
    return blocks


def main() -> None:
    wanted: dict[str, set[str]] = {s: set() for s in STYLES}
    for line in (ROOT / 'scripts' / 'icons.txt').read_text(encoding='utf8').splitlines():
        line = line.split('#')[0].strip()
        if line:
            style, name = line.split()
            wanted[style].add(name)
    names = set().union(*wanted.values())

    css = re.sub(r'/\*.*?\*/', '', CSS_IN.read_text(encoding='utf8'), flags=re.S)
    icon_rule = re.compile(r'^((?:\.fa-[\w-]+,?)+)\{--fa:"\\([0-9a-f]+)"\}$')

    base, icons, codepoints = [], [], {}
    for block in top_level_blocks(css):
        m = icon_rule.match(block)
        if m:
            selectors = [s for s in m.group(1).split(',') if s[4:] in names]
            if selectors:
                icons.append(f'{",".join(selectors)}{{--fa:"\\{m.group(2)}"}}')
                for s in selectors:
                    codepoints[s[4:]] = int(m.group(2), 16)
        elif not block.startswith('@font-face'):
            base.append(block)

    missing = names - codepoints.keys()
    if missing:
        sys.exit(f'Unknown icons: {", ".join(sorted(missing))}')

    FONTS_OUT.mkdir(parents=True, exist_ok=True)
    faces = []
    for style, (file, family, weight) in STYLES.items():
        if not wanted[style]:
            continue
        options = subset.Options()
        options.flavor = 'woff2'
        options.layout_features = ['*']
        font = subset.load_font(str(FA / 'webfonts' / file), options)
        subsetter = subset.Subsetter(options)
        subsetter.populate(unicodes=[codepoints[n] for n in wanted[style]])
        subsetter.subset(font)
        subset.save_font(font, str(FONTS_OUT / file), options)
        faces.append(
            f'@font-face{{font-family:"{family}";font-style:normal;font-weight:{weight};'
            f'font-display:block;src:url(../assets/fonts/{file}) format("woff2")}}'
        )
        print(f'{file}: {len(wanted[style])} glyphs, {(FONTS_OUT / file).stat().st_size} bytes')

    CSS_OUT.parent.mkdir(parents=True, exist_ok=True)
    CSS_OUT.write_text(
        '/* Generated by scripts/subset-icons.py from Font Awesome Pro 7. Do not edit. */\n'
        + '\n'.join(base + faces + sorted(icons)) + '\n',
        encoding='utf8',
    )
    print(f'icons.css: {CSS_OUT.stat().st_size} bytes')


if __name__ == '__main__':
    main()
